openapi: 3.0.0
info:
  title: CURLNEKO SNS
  version: 1.0.0
servers:
  - url: http://localhost:8083

paths:
  /auth/login:
    post:
      summary: To login
      tags:
        - auth
      requestBody:
        required: true
        description: A JSON object containing the login and password.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      security: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResult"
  /auth/verify:
    get:
      summary: To verify login status
      tags:
        - auth
      security:
        - cookieAuth: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyResult"

components:
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: jwt
  schemas:
    Result:
      type: object
      properties:
        status:
          type: boolean
        statusCode:
          type: string
        message:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    LoginResult:
      type: object
      properties:
        result:
          $ref: "#/components/schemas/Result"
    VerifyResult:
      type: object
      properties:
        result:
          $ref: "#/components/schemas/Result"

tags:
  - name: auth
    description: Everything about auth
